import process from "node:process";
import builtins from "builtin-modules";
import esbuild from "esbuild";

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */",
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "@codemirror/*", ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
