import type { AnnualReviewLanguage, ResolvedAnnualReviewLanguage } from "./types";

export function resolveAnnualReviewLanguage(
  language: AnnualReviewLanguage,
  appLanguage: string,
): ResolvedAnnualReviewLanguage {
  if (language === "zh" || language === "en") {
    return language;
  }
  return appLanguage.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function languageName(
  language: AnnualReviewLanguage,
  appLanguage: string,
): string {
  const resolved = resolveAnnualReviewLanguage(language, appLanguage);
  if (language === "system") {
    return resolved === "zh" ? "跟随 Obsidian" : "Follow Obsidian";
  }
  return language === "zh" ? "中文" : "English";
}

export const UI_TEXT = {
  en: {
    annualReview: "Annual Review",
    generateCommand: "Generate report",
    openDashboardCommand: "Open Review Board",
    rebuildIndexCommand: "Rebuild index",
    reportFolder: "Report folder",
    reportFolderDesc:
      "Generated annual review notes are written here and excluded from future scans.",
    includeFolders: "Include folders",
    includeFoldersDesc:
      "Comma-separated folder list. Leave empty to scan all Markdown files.",
    excludeFolders: "Exclude folders",
    excludeFoldersDesc: "Comma-separated folder list excluded from scans.",
    reportLanguage: "Report language",
    reportLanguageDesc: "Language used in generated annual review notes.",
    generatorLanguage: "Generator language",
    generatorLanguageDesc:
      "Language used by Annual Review settings and generation controls.",
    privacyMode: "Privacy mode",
    privacyModeDesc:
      "Private mode labels generated reports as privacy-sensitive without changing local-only behavior.",
    standard: "Standard",
    private: "Private",
    chinese: "中文",
    english: "English",
    followObsidian: "Follow Obsidian",
    includeLinkMetrics: "Include link metrics",
    includeFrontmatterMetrics: "Include frontmatter metrics",
    includeHeadingMetrics: "Include heading metrics",
    generateTitle: "Generate Annual Review",
    year: "Year",
    yearDesc: "The calendar year to scan by note created/modified timestamps.",
    runIncludeFoldersDesc:
      "Comma-separated folders for this run. Empty scans all Markdown files.",
    runExcludeFoldersDesc: "Comma-separated folders skipped for this run.",
    generate: "Generate",
    cancel: "Cancel",
    generating: (year: number) => `Generating ${year} annual review...`,
    progressTitle: (year: number) => `Generating ${year} annual review`,
    progressReadingVault: "Reading vault notes and link context",
    progressAiSummary: "Synthesizing themes and review-candidate reasons",
    progressRendering: "Rendering Obsidian Markdown and chart assets",
    progressWriting: "Writing annual review note",
    generated: (path: string) => `Annual review generated: ${path}`,
    failed: (message: string) => `Annual Review failed: ${message}`,
    rebuilt: (count: number) => `Annual Review index rebuilt: ${count} Markdown files.`,
    buildingPreview: "Building preview...",
    refreshingPreview: "Refreshing preview...",
    generateReport: "Generate report",
    preview: "Preview",
    rebuild: "Rebuild",
    scope: "Scope",
    include: "Include",
    exclude: "Exclude",
    allMarkdownFiles: "All Markdown files",
    none: "None",
    privacy: "Privacy",
    aiProvider: "Optional AI enrichment",
    chatGpt: "ChatGPT",
    index: "Index",
    rebuiltAt: (count: number, builtAt: string) => `${count} files, rebuilt ${builtAt}`,
    notBuiltYet: "Not built yet",
    noReportGenerated: "No report generated yet",
    report: (path: string) => `Report: ${path}`,
    openReport: "Open report",
    noPreviewData: "No preview data found for this year.",
    created: "Created",
    modified: "Modified",
    activeDays: "Active days",
    words: "Words",
    monthlyTrend: "Monthly Trend",
    dailyWordHeatmap: "Daily Word Heatmap",
    wordGrowth: "Word Growth",
    topTags: "Top Tags",
    topFolders: "Top Folders",
    topLinks: "Top Links",
    representativeNotes: "Representative Notes",
    reviewQueue: "Review Queue",
    noReviewCandidates: "No review candidates found for this year.",
    toReview: "To review",
    accepted: "Accepted",
    actions: "Actions",
    closed: "Closed",
    reviewed: "Reviewed",
    highlights: "Highlights",
    nextActions: "Next actions",
    ignored: "Ignored",
    missingEvidence: "missing evidence",
    decisionActions: "Decision actions",
    topicActions: "Topic actions",
    accept: "Accept",
    ignore: "Ignore",
    renameTopic: "Rename topic",
    mergeTopic: "Merge topic",
    addHighlight: "Add to annual highlights",
    addAction: "Add to actions",
    openSourceNote: "Open source note",
    renamePrompt: "Rename this topic",
    actionPrompt: "Action label",
    noDataFound: "No data found.",
    noteWords: (words: number) => `${words} words`,
    dayWords: (date: string, words: number) => `${date}: ${words} words`,
    dayWordsWithActivity: (
      date: string,
      words: number,
      created: number,
      modified: number,
    ) => `${date}: ${words} words, ${created} created, ${modified} modified`,
    monthGrowth: (month: string, gained: number, cumulative: number) =>
      `${month}: +${gained} words, ${cumulative} cumulative`,
    growthSummary: (gained: number, cumulative: number) => `+${gained} (${cumulative})`,
  },
  zh: {
    annualReview: "年度回顾",
    generateCommand: "生成报告",
    openDashboardCommand: "打开 Review Board",
    rebuildIndexCommand: "重建索引",
    reportFolder: "报告文件夹",
    reportFolderDesc: "生成的年度回顾笔记会写入这里，并从后续扫描中排除。",
    includeFolders: "包含文件夹",
    includeFoldersDesc: "用英文逗号分隔文件夹列表。留空则扫描全部 Markdown 文件。",
    excludeFolders: "排除文件夹",
    excludeFoldersDesc: "用英文逗号分隔要跳过的文件夹。",
    reportLanguage: "报告语言",
    reportLanguageDesc: "生成年度回顾笔记使用的语言。",
    generatorLanguage: "生成器语言",
    generatorLanguageDesc: "年度回顾设置与生成控件使用的语言。",
    privacyMode: "隐私模式",
    privacyModeDesc: "隐私模式会把生成报告标记为隐私敏感，但不改变本地优先行为。",
    standard: "标准",
    private: "私密",
    chinese: "中文",
    english: "English",
    followObsidian: "跟随 Obsidian",
    includeLinkMetrics: "包含链接指标",
    includeFrontmatterMetrics: "包含属性指标",
    includeHeadingMetrics: "包含标题指标",
    generateTitle: "生成年度回顾",
    year: "年份",
    yearDesc: "按笔记创建/修改时间扫描的日历年份。",
    runIncludeFoldersDesc:
      "本次运行包含的文件夹，用英文逗号分隔。留空则扫描全部 Markdown 文件。",
    runExcludeFoldersDesc: "本次运行跳过的文件夹，用英文逗号分隔。",
    generate: "生成",
    cancel: "取消",
    generating: (year: number) => `正在生成 ${year} 年度回顾...`,
    progressTitle: (year: number) => `正在生成 ${year} 年度回顾`,
    progressReadingVault: "读取 vault 笔记和双链上下文",
    progressAiSummary: "提炼主题和候选笔记推荐理由",
    progressRendering: "渲染 Obsidian Markdown 与图表资产",
    progressWriting: "写入年度回顾笔记",
    generated: (path: string) => `年度回顾已生成：${path}`,
    failed: (message: string) => `年度回顾生成失败：${message}`,
    rebuilt: (count: number) => `年度回顾索引已重建：${count} 个 Markdown 文件。`,
    buildingPreview: "正在构建预览...",
    refreshingPreview: "正在刷新预览...",
    generateReport: "生成报告",
    preview: "预览",
    rebuild: "重建",
    scope: "范围",
    include: "包含",
    exclude: "排除",
    allMarkdownFiles: "全部 Markdown 文件",
    none: "无",
    privacy: "隐私",
    aiProvider: "可选 AI 增强",
    chatGpt: "ChatGPT",
    index: "索引",
    rebuiltAt: (count: number, builtAt: string) => `${count} 个文件，重建于 ${builtAt}`,
    notBuiltYet: "尚未构建",
    noReportGenerated: "尚未生成报告",
    report: (path: string) => `报告：${path}`,
    openReport: "打开报告",
    noPreviewData: "这个年份没有预览数据。",
    created: "新建",
    modified: "修改",
    activeDays: "活跃日",
    words: "字词",
    monthlyTrend: "月度趋势",
    dailyWordHeatmap: "每日字词热力图",
    wordGrowth: "字词增长",
    topTags: "高频标签",
    topFolders: "高频文件夹",
    topLinks: "高频链接",
    representativeNotes: "代表笔记",
    reviewQueue: "候选审核队列",
    noReviewCandidates: "这个年份没有候选审核项。",
    toReview: "待审核",
    accepted: "已接受",
    actions: "行动",
    closed: "已关闭",
    reviewed: "已审核",
    highlights: "年度精选",
    nextActions: "下一步行动",
    ignored: "已忽略",
    missingEvidence: "证据缺失",
    decisionActions: "决策动作",
    topicActions: "主题动作",
    accept: "接受",
    ignore: "忽略",
    renameTopic: "重命名主题",
    mergeTopic: "合并主题",
    addHighlight: "加入年度精选",
    addAction: "加入行动",
    openSourceNote: "打开源笔记",
    renamePrompt: "重命名这个主题",
    actionPrompt: "行动标签",
    noDataFound: "未找到数据。",
    noteWords: (words: number) => `${words} 字词`,
    dayWords: (date: string, words: number) => `${date}: ${words} 字词`,
    dayWordsWithActivity: (
      date: string,
      words: number,
      created: number,
      modified: number,
    ) => `${date}: ${words} 字词，${created} 新建，${modified} 修改`,
    monthGrowth: (month: string, gained: number, cumulative: number) =>
      `${month}: +${gained} 字词，累计 ${cumulative}`,
    growthSummary: (gained: number, cumulative: number) => `+${gained}（${cumulative}）`,
  },
} as const;
