import type { AnnualReviewLanguage, ResolvedAnnualReviewLanguage } from "./types";

export function resolveAnnualReviewLanguage(
  language: AnnualReviewLanguage,
  appLanguage: string,
): ResolvedAnnualReviewLanguage {
  if (language === "zh" || language === "en") {
    return language;
  }
  return appLanguage.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function languageName(
  language: AnnualReviewLanguage,
  appLanguage: string,
): string {
  const resolved = resolveAnnualReviewLanguage(language, appLanguage);
  if (language === "system") {
    return resolved === "zh" ? "跟随 Obsidian" : "Follow Obsidian";
  }
  return language === "zh" ? "中文" : "English";
}

export const UI_TEXT = {
  en: {
    annualReview: "Annual Review",
    generateCommand: "Generate report",
    openDashboardCommand: "Open Review Board",
    rebuildIndexCommand: "Rebuild index",
    reportFolder: "Report folder",
    reportFolderDesc:
      "Generated annual review notes are written here and excluded from future scans.",
    includeFolders: "Include folders",
    includeFoldersDesc:
      "Comma-separated folder list. Leave empty to scan all Markdown files.",
    excludeFolders: "Exclude folders",
    excludeFoldersDesc: "Comma-separated folder list excluded from scans.",
    reportLanguage: "Report language",
    reportLanguageDesc: "Language used in generated annual review notes.",
    generatorLanguage: "Generator language",
    generatorLanguageDesc:
      "Language used by Annual Review settings and generation controls.",
    privacyMode: "Privacy mode",
    privacyModeDesc:
      "Private mode labels generated reports as privacy-sensitive without changing local-only behavior.",
    standard: "Standard",
    private: "Private",
    chinese: "中文",
    english: "English",
    followObsidian: "Follow Obsidian",
    includeLinkMetrics: "Include link metrics",
    includeFrontmatterMetrics: "Include frontmatter metrics",
    includeHeadingMetrics: "Include heading metrics",
    generateTitle: "Generate Review",
    reviewPreset: "Review period",
    reviewPresetDesc: "Choose an annual, quarterly, monthly, or custom date range.",
    annualPreset: "Annual",
    quarterlyPreset: "Quarterly",
    monthlyPreset: "Monthly",
    customPreset: "Custom range",
    year: "Year",
    yearDesc: "Used for annual, quarterly, and monthly review ranges.",
    quarter: "Quarter",
    quarterDesc: "Used when the review period is Quarterly.",
    month: "Month",
    monthDesc: "Used when the review period is Monthly.",
    customLabel: "Custom label",
    customLabelDesc: "Used as the generated report and asset folder name.",
    customStartDate: "Custom start date",
    customEndDate: "Custom end date",
    customDateDesc: "Use YYYY-MM-DD. The range is inclusive.",
    runIncludeFoldersDesc:
      "Comma-separated folders for this run. Empty scans all Markdown files.",
    runExcludeFoldersDesc: "Comma-separated folders skipped for this run.",
    generate: "Generate",
    cancel: "Cancel",
    generating: (label: string) => `Generating ${label}...`,
    progressTitle: (label: string) => `Generating ${label}`,
    progressReadingVault: "Reading vault notes and link context",
    progressAiSummary: "Synthesizing themes and evidence-note reasons",
    progressRendering: "Rendering Obsidian Markdown and chart assets",
    progressWriting: "Writing annual review note",
    generated: (path: string) => `Annual review generated: ${path}`,
    failed: (message: string) => `Annual Review failed: ${message}`,
    rebuilt: (count: number) => `Annual Review index rebuilt: ${count} Markdown files.`,
    buildingPreview: "Building preview...",
    refreshingPreview: "Refreshing preview...",
    generateReport: "Generate report",
    preview: "Preview",
    rebuild: "Rebuild",
    scope: "Scope",
    include: "Include",
    exclude: "Exclude",
    allMarkdownFiles: "All Markdown files",
    none: "None",
    privacy: "Privacy",
    aiProvider: "Optional AI enrichment",
    chatGpt: "ChatGPT",
    index: "Index",
    rebuiltAt: (count: number, builtAt: string) => `${count} files, rebuilt ${builtAt}`,
    notBuiltYet: "Not built yet",
    noReportGenerated: "No report generated yet",
    report: (path: string) => `Report: ${path}`,
    openReport: "Open report",
    noPreviewData: "No preview data found for this year.",
    created: "Created",
    modified: "Modified",
    activeDays: "Active days",
    words: "Words",
    monthlyTrend: "Monthly Trend",
    dailyWordHeatmap: "Daily Word Heatmap",
    wordGrowth: "Word Growth",
    topTags: "Top Tags",
    topFolders: "Top Folders",
    topLinks: "Top Links",
    representativeNotes: "Representative Notes",
    reviewQueue: "Theme Hypotheses",
    degradedReviewQueue: "Local clues (AI unavailable)",
    degradedReviewQueueDescription:
      "These are degraded local clues, not final AI semantic themes. Use them only after checking the source notes.",
    noReviewCandidates: "No theme hypotheses found for this year.",
    toReview: "To review",
    accepted: "Accepted proposal",
    actions: "Decisions",
    closed: "Closed",
    reviewed: "Reviewed",
    highlights: "Evidence clusters",
    nextActions: "Reflection prompts",
    ignored: "Ignored",
    currentNoteSummary: "Why proposed",
    connectionExplanation: "Connection explanation",
    localSignals: "Local signals",
    uncertainty: "Uncertainty",
    reviewCaution: "Review caution",
    selectedEvidence: "Selected evidence",
    essentialMetadata: "Essential metadata",
    linkedNotes: "Linked notes",
    missingEvidence: "missing evidence",
    decisionActions: "Decision",
    pendingDecisionActions: "Theme decision",
    acceptedDecisionActions: "Accepted proposal",
    actionDecisionActions: "Decision",
    closedDecisionActions: "Closed decision",
    topicActions: "Theme actions",
    accept: "Accept",
    ignore: "Ignore",
    renameTopic: "Rename",
    renameTitle: "Theme title",
    saveRename: "Save rename",
    evidenceComment: "Evidence comment",
    saveComment: "Save comment",
    mergeTopic: "Merge",
    addHighlight: "Add evidence cluster",
    addAction: "Add decision",
    openSourceNote: "Open Source Note",
    renamePrompt: "Rename this theme hypothesis",
    actionPrompt: "Decision label",
    noDataFound: "No data found.",
    noteWords: (words: number) => `${words} words`,
    dayWords: (date: string, words: number) => `${date}: ${words} words`,
    dayWordsWithActivity: (
      date: string,
      words: number,
      created: number,
      modified: number,
    ) => `${date}: ${words} words, ${created} created, ${modified} modified`,
    monthGrowth: (month: string, gained: number, cumulative: number) =>
      `${month}: +${gained} words, ${cumulative} cumulative`,
    growthSummary: (gained: number, cumulative: number) => `+${gained} (${cumulative})`,
  },
  zh: {
    annualReview: "年度回顾",
    generateCommand: "生成报告",
    openDashboardCommand: "打开 Review Board",
    rebuildIndexCommand: "重建索引",
    reportFolder: "报告文件夹",
    reportFolderDesc: "生成的年度回顾笔记会写入这里，并从后续扫描中排除。",
    includeFolders: "包含文件夹",
    includeFoldersDesc: "用英文逗号分隔文件夹列表。留空则扫描全部 Markdown 文件。",
    excludeFolders: "排除文件夹",
    excludeFoldersDesc: "用英文逗号分隔要跳过的文件夹。",
    reportLanguage: "报告语言",
    reportLanguageDesc: "生成年度回顾笔记使用的语言。",
    generatorLanguage: "生成器语言",
    generatorLanguageDesc: "年度回顾设置与生成控件使用的语言。",
    privacyMode: "隐私模式",
    privacyModeDesc: "隐私模式会把生成报告标记为隐私敏感，但不改变本地优先行为。",
    standard: "标准",
    private: "私密",
    chinese: "中文",
    english: "English",
    followObsidian: "跟随 Obsidian",
    includeLinkMetrics: "包含链接指标",
    includeFrontmatterMetrics: "包含属性指标",
    includeHeadingMetrics: "包含标题指标",
    generateTitle: "生成回顾",
    reviewPreset: "回顾范围",
    reviewPresetDesc: "选择年度、季度、月度或自定义日期范围。",
    annualPreset: "年度",
    quarterlyPreset: "季度",
    monthlyPreset: "月度",
    customPreset: "自定义范围",
    year: "年份",
    yearDesc: "用于年度、季度与月度回顾范围。",
    quarter: "季度",
    quarterDesc: "当回顾范围为季度时使用。",
    month: "月份",
    monthDesc: "当回顾范围为月度时使用。",
    customLabel: "自定义标题",
    customLabelDesc: "用于生成报告和图表资源文件夹名称。",
    customStartDate: "自定义开始日期",
    customEndDate: "自定义结束日期",
    customDateDesc: "使用 YYYY-MM-DD，包含起止日期。",
    runIncludeFoldersDesc:
      "本次运行包含的文件夹，用英文逗号分隔。留空则扫描全部 Markdown 文件。",
    runExcludeFoldersDesc: "本次运行跳过的文件夹，用英文逗号分隔。",
    generate: "生成",
    cancel: "取消",
    generating: (label: string) => `正在生成 ${label}...`,
    progressTitle: (label: string) => `正在生成 ${label}`,
    progressReadingVault: "读取 vault 笔记和双链上下文",
    progressAiSummary: "提炼主题和候选笔记推荐理由",
    progressRendering: "渲染 Obsidian Markdown 与图表资产",
    progressWriting: "写入年度回顾笔记",
    generated: (path: string) => `年度回顾已生成：${path}`,
    failed: (message: string) => `年度回顾生成失败：${message}`,
    rebuilt: (count: number) => `年度回顾索引已重建：${count} 个 Markdown 文件。`,
    buildingPreview: "正在构建预览...",
    refreshingPreview: "正在刷新预览...",
    generateReport: "生成报告",
    preview: "预览",
    rebuild: "重建",
    scope: "范围",
    include: "包含",
    exclude: "排除",
    allMarkdownFiles: "全部 Markdown 文件",
    none: "无",
    privacy: "隐私",
    aiProvider: "可选 AI 增强",
    chatGpt: "ChatGPT",
    index: "索引",
    rebuiltAt: (count: number, builtAt: string) => `${count} 个文件，重建于 ${builtAt}`,
    notBuiltYet: "尚未构建",
    noReportGenerated: "尚未生成报告",
    report: (path: string) => `报告：${path}`,
    openReport: "打开报告",
    noPreviewData: "这个年份没有预览数据。",
    created: "新建",
    modified: "修改",
    activeDays: "活跃日",
    words: "字词",
    monthlyTrend: "月度趋势",
    dailyWordHeatmap: "每日字词热力图",
    wordGrowth: "字词增长",
    topTags: "高频标签",
    topFolders: "高频文件夹",
    topLinks: "高频链接",
    representativeNotes: "代表笔记",
    reviewQueue: "主题假设",
    degradedReviewQueue: "本地线索（AI 不可用）",
    degradedReviewQueueDescription:
      "这些是降级的本地线索，不是最终 AI 语义主题；请先打开源笔记确认。",
    noReviewCandidates: "这个年份没有主题假设。",
    toReview: "待审核",
    accepted: "已采纳提案",
    actions: "决策",
    closed: "已关闭",
    reviewed: "已审核",
    highlights: "证据簇",
    nextActions: "复盘提示",
    ignored: "已忽略",
    currentNoteSummary: "为什么提出",
    connectionExplanation: "连接解释",
    localSignals: "本地信号",
    uncertainty: "不确定性",
    reviewCaution: "复核提示",
    selectedEvidence: "当前证据",
    essentialMetadata: "必要元数据",
    linkedNotes: "关联笔记",
    missingEvidence: "证据缺失",
    decisionActions: "决策",
    pendingDecisionActions: "主题决策",
    acceptedDecisionActions: "已采纳提案",
    actionDecisionActions: "决策",
    closedDecisionActions: "已关闭决策",
    topicActions: "主题操作",
    accept: "接受",
    ignore: "忽略",
    renameTopic: "重命名",
    renameTitle: "主题标题",
    saveRename: "保存重命名",
    evidenceComment: "证据评论",
    saveComment: "保存评论",
    mergeTopic: "合并",
    addHighlight: "加入证据簇",
    addAction: "加入决策",
    openSourceNote: "打开源笔记",
    renamePrompt: "重命名这个主题假设",
    actionPrompt: "决策标签",
    noDataFound: "未找到数据。",
    noteWords: (words: number) => `${words} 字词`,
    dayWords: (date: string, words: number) => `${date}: ${words} 字词`,
    dayWordsWithActivity: (
      date: string,
      words: number,
      created: number,
      modified: number,
    ) => `${date}: ${words} 字词，${created} 新建，${modified} 修改`,
    monthGrowth: (month: string, gained: number, cumulative: number) =>
      `${month}: +${gained} 字词，累计 ${cumulative}`,
    growthSummary: (gained: number, cumulative: number) => `+${gained}（${cumulative}）`,
  },
} as const;
